client.out: main.c ../common/TCPClientUtility.c ../common/ErrorHelper.c ../common/DelimiterFramer.c ../common/LoginEncodingText.c ../common/MessageEncodingText.c
	gcc -o client.out main.c ../common/TCPClientUtility.c ../common/ErrorHelper.c ../common/DelimiterFramer.c ../common/LoginEncodingText.c ../common/MessageEncodingText.c -I.
